### ISSUE TITLE
attribute 'virtual_server' is mandatory

### ISSUE THREAD

**Issue by cathode911** [saltstack-formulas/keepalived-formula#21]
If 'virtual_server' key is not used in pillar at all, formula fails with the following error

```
servername.domainname.com:
  Name: keepalived - Function: pkg.installed - Result: Clean Started: - 01:58:14.758205 Duration: 570.989 ms
----------
          ID: keepalived-config-file-file-managed
    Function: file.managed
        Name: /etc/keepalived/keepalived.conf
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'virtual_server'
              /var/cache/salt/minion/files/base/keepalived/macro.jinja(37):
              ---
              [...]
                        {%- endif -%}
                        {{- item[key]|indent(carryIndent, True) }} {{ print_config(item[value], recurse=recurse, indent=forwardIndent) -}}
                      {%- endif -%}
                    {%- endfor -%}
                  {%- else -%}
                    {%- for item in data -%}    <======================
                      {{- print_config(item, indent=indent) -}}
                    {%- endfor -%}
                  {%- endif -%}
                  {%- if recurse > 0 -%}
                    {{- '}'|indent(indent - 2, True) -}}{{ '\n' }}
              [...]
              ---
     Started: 01:58:15.331332
    Duration: 61.149 ms
```

If 'virtual_server' key exists, formula works as expected.

**Comment by kleinstuff** [comment]
Are you sure that this is still not working?
Tested with this pillar and it worked perfectly:
```
keepalived:
  config:
    global_defs:
      router_id: OVPN
    vrrp_sync_group:
      vrrp_group:
        group:
          - VRRP_IPV4
          - VRRP_IPV6
    vrrp_instance:
      VRRP_IPV4:
        state: MASTER
        interface: eth0
        virtual_router_id: 51
        priority: 100
        advert_int: 1
        authentication:
          auth_type: PASS
          auth_pass: 1111
        unicast_peer:
          192.168.122.132:
        unicast_src_ip: 192.168.122.131
        virtual_ipaddress:
          - 192.168.122.130 dev eth0
```
