### ISSUE TITLE
formula does not support vrrp_sync_group

### ISSUE THREAD

**Issue by cathode911** [saltstack-formulas/keepalived-formula#22]
Formula does not support keepalived feature 'vrrp_sync_group'
Suggested pillar example:

```
keepalived:
  config:
  <omitted>
    vrrp_sync_group:
      anygroupname:
        - service1
        - service2
    vrrp_instance:
    <omitted>
```
